[global]
checkNewVersion = false

[api]
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[providers]
  [providers.docker]
  exposedByDefault = false
  endpoint = "unix:///var/run/docker.sock"

[certificatesResolvers.myresolver.acme]
email = "hantsawilliams@gmail.com"
storage = "acme.json"
[certificatesResolvers.myresolver.acme.httpChallenge]
entryPoint = "http"
[certificatesResolvers.myresolver.acme.tlsChallenge]
entryPoint = "http"
[[certificatesResolvers.myresolver.acme.domains]]
main = "hantswilliams.com"
sans = ["*.hantswilliams.com"]

[http.routers]
  [http.routers.app1]
  rule = "Host(`hantswilliams.com`)"
  service = "app1"
  entryPoints = ["https"]
  [http.routers.app2]
  rule = "Host(`sub1.hantswilliams.com`)"
  service = "app2"
  entryPoints = ["https"]
  [http.routers.app3]
  rule = "Host(`sub2.hantswilliams.com`)"
  service = "app3"
  entryPoints = ["https"]

[http.services]
  [http.services.app1.loadBalancer]
  [[http.services.app1.loadBalancer.servers]]
  url = "http://34.171.76.221:80"
  [http.services.app2.loadBalancer]
  [[http.services.app2.loadBalancer.servers]]
  url = "http://34.170.61.70:80"
  [http.services.app3.loadBalancer]
  [[http.services.app3.loadBalancer.servers]]
  url = "http://35.194.42.230:80"
