# Global configuration
global:
  checkNewVersion: false

# API and dashboard configuration
api:
  dashboard: true

# Entry points
entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

# HTTPS configuration
certificatesResolvers:
  myresolver:
    acme:
      email: hantsawilliams@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
      tlsChallenge:
        entryPoint: http
      domains:
        - main: hantswilliams.com
          sans:
            - "*.hantswilliams.com"

# Routers
http:
  routers:
    app1:
      rule: "Host(`hantswilliams.com`)"
      service: "app1"
      entryPoints:
        - "https"
    app2:
      rule: "Host(`sub1.hantswilliams.com`)"
      service: "app2"
      entryPoints:
        - "https"
    app3:
      rule: "Host(`sub2.hantswilliams.com`)"
      service: "app3"
      entryPoints:
        - "https"

  # Services
  services:
    app1:
      loadBalancer:
        servers:
          - url: "http:/34.171.76.221:80"
    app2:
      loadBalancer:
        servers:
          - url: "http://34.170.61.70:80"
    app3:
      loadBalancer:
        servers:
          - url: "http://35.194.42.230:80"
