# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: true

# Logging configuration
log:
  level: DEBUG

# Entry points configuration
entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8080"

# Providers configuration
providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik
    watch: true

# HTTP routers configuration
http:
  routers:
    router-1:
      rule: "Host(`hantswilliams.com`)"
      service: "service-1"
    router-2:
      rule: "Host(`subdomain.hantswilliams.com`)"
      service: "service-2"
    router-3:
      rule: "Host(`traefik.hantswilliams.com`) && Path(`/`)"
      service: "api@internal"
      entryPoints:
        - "web"

  # HTTP services configuration
  services:
    service-1:
      loadBalancer:
        servers:
          - url: "http://34.171.76.221:80"
    service-2:
      loadBalancer:
        servers:
          - url: "http://34.170.61.70:80"

    


