[global]
  checkNewVersion = true

[log]
  level = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"

[api]
  dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false
  [providers.file]
    filename = "/etc/traefik/dynamic.yml"
    watch = true

[http]
  [http.routers]
    [http.routers.socialcomprehend]
      rule = "Host(`hantswilliams.com`)"
      service = "socialcomprehend"
      [http.routers.socialcomprehend.tls]
        certResolver = "le"
    [http.routers.api]
      rule = "Host(`api.hantswilliams.com`)"
      service = "api"
      [http.routers.api.tls]
        certResolver = "le"
    [http.routers.database]
      rule = "Host(`database.hantswilliams.com`)"
      service = "database"
      [http.routers.database.tls]
        certResolver = "le"

  [http.services]
    [http.services.socialcomprehend.loadBalancer]
      [[http.services.socialcomprehend.loadBalancer.servers]]
        url = "http:/34.171.76.221:80"
    [http.services.api.loadBalancer]
      [[http.services.api.loadBalancer.servers]]
        url = "http://34.170.61.70:80"
    [http.services.database.loadBalancer]
      [[http.services.database.loadBalancer.servers]]
        url = "http://35.194.42.230:80"
