version: '3'

services:
  flask-app:
    build: .
    container_name: flask-app
    restart: always
    environment:
      - "VIRTUAL_HOST=hantsawilliams.com,www.hantsawilliams.com"
      - "VIRTUAL_PORT=80"
    expose:
      - "80"
    networks:
      my-network:
        aliases:
          - flask-app

networks:
  my-network: